## 00

from pathlib import Path

# ---- EDIT THIS ONE LINE ONLY ----
BASE_DIR = Path(r"C:\Users\sruja\Downloads\Data Collection")
CYCLE_DIR = BASE_DIR / "2011-2012"
CODE_DIR = BASE_DIR / "Code"

# Input folders
CM_DIR = CYCLE_DIR / "cm12"
CN_DIR = CYCLE_DIR / "cn12"
CCL_DIR = CYCLE_DIR / "ccl12"
INDIV_DIR = CYCLE_DIR / "indiv12"
PAS2_DIR = CYCLE_DIR / "pas212"

# Output folder
OUT_DIR = CYCLE_DIR / "outputs"
OUT_DIR.mkdir(parents=True, exist_ok=True)

# Behavior
SENATE_ONLY = True
CHUNKSIZE = 2_000_000

# ---- File schemas (from your headers) ----
CM_COLS = [
    "CMTE_ID","CMTE_NM","TRES_NM","CMTE_ST1","CMTE_ST2","CMTE_CITY","CMTE_ST",
    "CMTE_ZIP","CMTE_DSGN","CMTE_TP","CMTE_PTY_AFFILIATION","CMTE_FILING_FREQ",
    "ORG_TP","CONNECTED_ORG_NM","CAND_ID"
]

CN_COLS = [
    "CAND_ID","CAND_NAME","CAND_PTY_AFFILIATION","CAND_ELECTION_YR","CAND_OFFICE_ST",
    "CAND_OFFICE","CAND_OFFICE_DISTRICT","CAND_ICI","CAND_STATUS","CAND_PCC",
    "CAND_ST1","CAND_ST2","CAND_CITY","CAND_ST","CAND_ZIP"
]

CCL_COLS = [
    "CAND_ID","CAND_ELECTION_YR","FEC_ELECTION_YR","CMTE_ID","CMTE_TP","CMTE_DSGN","LINKAGE_ID"
]

INDIV_COLS = [
    "CMTE_ID","AMNDT_IND","RPT_TP","TRANSACTION_PGI","IMAGE_NUM","TRANSACTION_TP","ENTITY_TP",
    "NAME","CITY","STATE","ZIP_CODE","EMPLOYER","OCCUPATION","TRANSACTION_DT","TRANSACTION_AMT",
    "OTHER_ID","TRAN_ID","FILE_NUM","MEMO_CD","MEMO_TEXT","SUB_ID"
]

ITPAS2_COLS = [
    "CMTE_ID","AMNDT_IND","RPT_TP","TRANSACTION_PGI","IMAGE_NUM","TRANSACTION_TP","ENTITY_TP",
    "NAME","CITY","STATE","ZIP_CODE","EMPLOYER","OCCUPATION","TRANSACTION_DT","TRANSACTION_AMT",
    "OTHER_ID","CAND_ID","TRAN_ID","FILE_NUM","MEMO_CD","MEMO_TEXT","SUB_ID"
]
